-- Create TEST_TABLE
CREATE TABLE TEST_TABLE(
BIGINT_COL BIGINT NOT NULL,
BOOLEAN_COL BOOLEAN NOT NULL,
CHAR_COL CHAR NOT NULL,
DATE_COL DATE NOT NULL,
DECIMAL_COL DECIMAL NOT NULL,
DOUBLE_COL DOUBLE NOT NULL,
FLOAT_COL FLOAT(52) NOT NULL,
INTEGER_COL INTEGER NOT NULL,
NUMERIC_COL NUMERIC(5,2) NOT NULL,
REAL_COL REAL NOT NULL,
SMALLINT_COL SMALLINT NOT NULL,
TIME_COL TIME NOT NULL,
TIMESTAMP_COL TIMESTAMP NOT NULL,
VARCHAR_COL VARCHAR(30) NOT NULL);

